platform :ios, "15.0"

use_frameworks!

target "FrameworkBuilder" do
  pod "PrebidMobile", :path => "../"
  pod "PrebidMobileGAMEventHandlers", :path => "../"
  pod "Google-Mobile-Ads-SDK", ">=12.0.0"
end
